# Generated by Django 3.0.8 on 2020-07-24 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20200724_1909'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offsite',
            name='crop',
        ),
        migrations.AddField(
            model_name='offsite',
            name='crop',
            field=models.ManyToManyField(related_name='offsite_crops', to='core.Crop'),
        ),
    ]
