# Generated by Django 3.0.8 on 2020-07-26 01:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20200726_0115'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farm',
            name='hours',
        ),
        migrations.RemoveField(
            model_name='offsite',
            name='hours',
        ),
        migrations.AddField(
            model_name='openhours',
            name='farm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='farm_hours', to='core.Farm'),
        ),
        migrations.AddField(
            model_name='openhours',
            name='offsite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offsite_hours', to='core.OffSite'),
        ),
    ]
