# Generated by Django 3.0.8 on 2020-07-26 18:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mapbox_location_field.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0013_auto_20200726_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farm',
            name='address',
            field=mapbox_location_field.models.AddressAutoHiddenField(map_id='map', null=True),
        ),
        migrations.AlterField(
            model_name='farm',
            name='location',
            field=mapbox_location_field.models.LocationField(map_attrs={}, null=True),
        ),
        migrations.AlterField(
            model_name='farm',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='farmers', to=settings.AUTH_USER_MODEL),
        ),
    ]
