# Generated by Django 3.0.8 on 2020-07-26 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20200726_1836'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='openhours',
            name='farm',
        ),
        migrations.RemoveField(
            model_name='openhours',
            name='offsite',
        ),
        migrations.AddField(
            model_name='farm',
            name='hours',
            field=models.ManyToManyField(related_name='hours', to='core.OpenHours'),
        ),
    ]
