# Generated by Django 3.0.8 on 2020-07-26 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20200726_1846'),
    ]

    operations = [
        migrations.AddField(
            model_name='offsite',
            name='hours',
            field=models.ManyToManyField(related_name='offsite_hours', to='core.OpenHours'),
        ),
    ]
