# Generated by Django 3.0.8 on 2020-07-27 15:50

from django.db import migrations, models
import mapbox_location_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20200726_2317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farm',
            name='location',
            field=mapbox_location_field.models.LocationField(blank=True, map_attrs={}, null=True),
        ),
        migrations.AlterField(
            model_name='farm',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='farms', to='core.Tag'),
        ),
    ]
