# Generated by Django 3.0.8 on 2020-07-28 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_farm_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farm',
            name='address',
        ),
        migrations.RemoveField(
            model_name='place',
            name='address',
        ),
    ]
