# Generated by Django 3.0.8 on 2020-07-28 01:44

from django.db import migrations, models
import mapbox_location_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_auto_20200728_0140'),
    ]

    operations = [
        migrations.AddField(
            model_name='farm',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='farm',
            name='location',
            field=mapbox_location_field.models.LocationField(blank=True, default='', map_attrs={'center': [0, 0], 'geocoder': True, 'marker_color': 'blue', 'track_location_button': True}, null=True),
        ),
        migrations.AddField(
            model_name='offsite',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='offsite',
            name='location',
            field=mapbox_location_field.models.LocationField(blank=True, default='', map_attrs={'center': [0, 0], 'geocoder': True, 'marker_color': 'blue', 'track_location_button': True}, null=True),
        ),
        migrations.DeleteModel(
            name='Place',
        ),
    ]
