# Generated by Django 3.0.8 on 2020-07-28 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_place'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='address',
        ),
    ]
