# Generated by Django 3.0.8 on 2020-07-28 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_remove_place_address'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Place',
        ),
    ]
