# Generated by Django 3.0.8 on 2020-07-28 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_auto_20200728_1637'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offsite',
            name='address',
        ),
        migrations.RemoveField(
            model_name='offsite',
            name='farm',
        ),
        migrations.RemoveField(
            model_name='offsite',
            name='hours',
        ),
        migrations.RemoveField(
            model_name='offsite',
            name='location',
        ),
    ]
