# Generated by Django 3.0.8 on 2020-07-28 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_auto_20200728_1643'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crop',
            name='offsite',
        ),
    ]
