# Generated by Django 3.0.8 on 2020-07-28 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_remove_crop_offsite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farm',
            name='address',
        ),
        migrations.AddField(
            model_name='farm',
            name='city',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='City'),
        ),
        migrations.AddField(
            model_name='farm',
            name='state',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='State'),
        ),
        migrations.AddField(
            model_name='farm',
            name='street_address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Street Address Line 2'),
        ),
        migrations.AddField(
            model_name='farm',
            name='zip_code',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Zip'),
        ),
    ]
