# Generated by Django 3.0.8 on 2020-07-28 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_auto_20200728_1825'),
    ]

    operations = [
        migrations.AddField(
            model_name='farm',
            name='street_address_line_2',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Street Address Line 2'),
        ),
        migrations.AlterField(
            model_name='farm',
            name='street_address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Street Address'),
        ),
    ]
