# Generated by Django 3.0.8 on 2020-07-29 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_auto_20200728_1826'),
        ('core', '0020_auto_20200728_1702'),
    ]

    operations = [
    ]
