# Generated by Django 3.0.8 on 2020-07-29 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_auto_20200729_1537'),
        ('core', '0034_merge_20200729_0055'),
    ]

    operations = [
    ]
