# Generated by Django 3.0.8 on 2020-07-29 16:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0035_merge_20200729_1636'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farm',
            name='farmer',
        ),
        migrations.AddField(
            model_name='farm',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='farms', to=settings.AUTH_USER_MODEL),
        ),
    ]
