# Generated by Django 3.0.8 on 2020-07-30 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_auto_20200729_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farm',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Farm Name'),
        ),
    ]
