# Generated by Django 3.0.8 on 2020-07-31 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_auto_20200731_0410'),
    ]

    operations = [
        migrations.AddField(
            model_name='offsite',
            name='city',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='City'),
        ),
        migrations.AddField(
            model_name='offsite',
            name='farm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offsites', to='core.Farm'),
        ),
        migrations.AddField(
            model_name='offsite',
            name='last_updated',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='offsite',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='offsite',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='offsite',
            name='offsite_hour',
            field=models.ManyToManyField(related_name='offsite_hours', to='core.OpenHours'),
        ),
        migrations.AddField(
            model_name='offsite',
            name='state',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='State'),
        ),
        migrations.AddField(
            model_name='offsite',
            name='street_address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Street Address'),
        ),
        migrations.AddField(
            model_name='offsite',
            name='street_address_line_2',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Street Address Line 2'),
        ),
        migrations.AddField(
            model_name='offsite',
            name='zip_code',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Zip'),
        ),
    ]
