# Generated by Django 3.0.8 on 2020-07-31 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_auto_20200731_0410'),
    ]

    operations = [
        migrations.AddField(
            model_name='farm',
            name='about_us',
            field=models.TextField(blank=True, max_length=1500, null=True),
        ),
    ]
