# Generated by Django 3.0.8 on 2020-07-31 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_farm_about_us'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='customer',
            new_name='user',
        ),
        migrations.AddField(
            model_name='farm',
            name='favorited_by',
            field=models.ManyToManyField(blank=True, related_name='favorite_farms', to='core.Customer'),
        ),
    ]
