# Generated by Django 3.0.8 on 2020-08-01 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_auto_20200801_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='openhours',
            name='weekday',
            field=models.CharField(blank=True, choices=[('MON', 'Monday'), ('TUE', 'Tuesday'), ('WED', 'Wednesday'), ('THU', 'Thursday'), ('FRI', 'Friday'), ('SAT', 'Saturday'), ('SUN', 'Sunday')], max_length=3, null=True),
        ),
    ]
