# Generated by Django 3.0.8 on 2020-08-02 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_auto_20200801_1811'),
        ('core', '0042_auto_20200731_2106'),
    ]

    operations = [
    ]
