# Generated by Django 3.0.8 on 2020-08-02 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_merge_20200802_1641'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farm',
            name='favorited_by',
        ),
    ]
