# Generated by Django 3.0.8 on 2020-08-03 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_merge_20200802_1913'),
        ('core', '0043_merge_20200802_1937'),
    ]

    operations = [
    ]
