# Generated by Django 3.0.8 on 2020-08-03 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_auto_20200731_1857'),
        ('core', '0043_merge_20200802_1913'),
    ]

    operations = [
    ]
