# Generated by Django 3.0.8 on 2020-08-03 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_merge_20200803_1353'),
        ('core', '0044_merge_20200803_1412'),
        ('core', '0044_merge_20200803_1417'),
    ]

    operations = [
    ]
