# Generated by Django 3.0.8 on 2020-08-04 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_auto_20200803_1523'),
        ('core', '0044_remove_farm_favorited_by'),
    ]

    operations = [
    ]
