# Generated by Django 3.0.8 on 2020-08-04 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_merge_20200804_1352'),
        ('core', '0048_merge_20200804_1339'),
    ]

    operations = [
    ]
