# Generated by Django 3.0.8 on 2020-08-04 18:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0049_merge_20200804_1813'),
    ]

    operations = [
        migrations.AddField(
            model_name='farm',
            name='favorited_by',
            field=models.ManyToManyField(blank=True, related_name='favorite_farms', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='offsite',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Offsite Type'),
        ),
    ]
