# Generated by Django 3.0.8 on 2020-08-04 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0050_auto_20200804_1813'),
    ]

    operations = [
        migrations.AddField(
            model_name='offsite',
            name='about_us',
            field=models.TextField(blank=True, max_length=1500, null=True),
        ),
    ]
