# Generated by Django 3.0.8 on 2020-08-04 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0051_offsite_about_us'),
    ]

    operations = [
        migrations.AddField(
            model_name='crop',
            name='offsite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offsite_crops', to='core.OffSite'),
        ),
    ]
